// This code was generated by Repose.

package api

// Error is a generated type based on a schema.
type Error struct {
	Code    int32  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}

// NewPet is a generated type based on a schema.
type NewPet struct {
	Name string  `json:"name,omitempty"`
	Tag  *string `json:"tag,omitempty"`
}

// Pet is a generated type based on a schema.
type Pet struct {
	NewPet
	PetFragment1
}

// PetFragment1 is a part of Pet.
type PetFragment1 struct {
	ID int64 `json:"id,omitempty"`
}
